import { Badge, Card, Code, Flex, Grid, Heading, Section, Separator, Text } from "@radix-ui/themes";
import { ExclamationTriangleIcon } from "@radix-ui/react-icons";
import { AnalysisReport } from "@/types/analysis";

interface RepoSummaryCardProps {
  report: AnalysisReport | null;
}

const riskColor = (score: number) => (score > 0.6 ? "red" : score > 0.3 ? "yellow" : "green");

const severityColor: Record<AnalysisReport["reviews"][number]["severity"], string> = {
  error: "red",
  warning: "yellow",
  info: "gray"
};

export function RepoSummaryCard({ report }: RepoSummaryCardProps) {
  if (!report) return null;

  const totalLoc = report.snapshot.files.reduce((acc, file) => acc + file.linesOfCode, 0);

  return (
    <Flex direction="column" gap="5" mt="6">
      <Card>
        <Flex direction="column" gap="2">
          <Heading as="h2" size="6">Repository Snapshot</Heading>
          <Text color="gray" size="2">{report.snapshot.repoUrl}</Text>
          <Grid columns={{ initial: "1", sm: "3" }} gap="3">
            <InfoTile label="Branch" value={report.snapshot.branch || "main"} />
            <InfoTile label="Files Analyzed" value={report.snapshot.files.length.toString()} />
            <InfoTile label="Estimated LOC" value={totalLoc.toString()} />
          </Grid>
        </Flex>
      </Card>

      <Section size="1">
        <Heading as="h2" size="6" mb="3">Code Review</Heading>
        <Flex direction="column" gap="3">
          {report.reviews.length === 0 && (
            <Card>
              <Text size="2" color="gray">No review comments were generated.</Text>
            </Card>
          )}
          {report.reviews.map((r, i) => (
            <Card key={`${r.file}-${i}`}>
              <Flex gap="3" align="start" justify="between">
                <Flex gap="3" align="start">
                  <ExclamationTriangleIcon color={severityColor[r.severity]} />
                  <div>
                    <Flex gap="2" align="center">
                      <Badge color={severityColor[r.severity]} radius="full">{r.severity.toUpperCase()}</Badge>
                      <Code>{r.file}</Code>
                      {r.line && <Text size="1" color="gray">Line {r.line}</Text>}
                    </Flex>
                    <Text size="2" as="p" mt="1">{r.message}</Text>
                    {r.suggestion && (
                      <Text as="p" color="gray" size="2" mt="1">Suggestion: {r.suggestion}</Text>
                    )}
                  </div>
                </Flex>
              </Flex>
            </Card>
          ))}
        </Flex>
      </Section>

      <Section size="1">
        <Heading as="h2" size="6" mb="3">Generated Tests</Heading>
        <Flex direction="column" gap="3">
          {report.tests.length === 0 && (
            <Card>
              <Text size="2" color="gray">No tests were generated by the agent.</Text>
            </Card>
          )}
          {report.tests.map((t, i) => (
            <Card key={`${t.file}-${i}`}>
              <Flex justify="between" align="start" gap="2">
                <div>
                  <Heading as="h3" size="4">Test for <Code>{t.target}</Code></Heading>
                  <Text size="1" color="gray" as="p">Framework: {t.framework}</Text>
                  <Text size="1" color="gray" as="p">Suggested file: {t.file}</Text>
                </div>
                <Badge color="indigo" variant="soft">Auto-generated</Badge>
              </Flex>
              <Separator my="3" size="4" />
              <pre style={{ whiteSpace: "pre-wrap" }}><code>{t.code}</code></pre>
            </Card>
          ))}
        </Flex>
      </Section>

      <Section size="1">
        <Heading as="h2" size="6" mb="3">Regression Risks</Heading>
        <Flex direction="column" gap="3">
          {report.risks.length === 0 && (
            <Card>
              <Text size="2" color="gray">No risk items were identified.</Text>
            </Card>
          )}
          {report.risks.map((risk, i) => (
            <Card key={`${risk.module}-${i}`}>
              <Flex align="center" justify="between">
                <Code>{risk.module}</Code>
                <Badge color={riskColor(risk.riskScore)} radius="full">
                  {(risk.riskScore * 100).toFixed(0)}% Risk
                </Badge>
              </Flex>
              <Text as="p" size="2" color="gray" mt="1">{risk.rationale}</Text>
            </Card>
          ))}
        </Flex>
      </Section>
    </Flex>
  );
}

interface InfoTileProps {
  label: string;
  value: string;
}

function InfoTile({ label, value }: InfoTileProps) {
  return (
    <Card>
      <Flex direction="column" gap="1">
        <Text color="gray" size="2">{label}</Text>
        <Text weight="bold" size="4">{value}</Text>
      </Flex>
    </Card>
  );
}
