import { useMemo, useState } from "react";
import { Container, Heading, Text, Flex, Card } from "@radix-ui/themes";
import { AuraLogo } from "@/components/AuraLogo";
import { RepoForm } from "@/components/RepoForm";
import { RepoSummaryCard } from "@/components/RepoSummaryCard";
import { AnalysisReport } from "@/types/analysis";

export default function Home() {
  const [report, setReport] = useState<AnalysisReport | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [isPending, setIsPending] = useState(false);

  const introText = useMemo(
    () => [
      "Point AURA at any public GitHub repo to get an instant mock analysis report.",
      "Results are generated by lightweight agents and surfaced with review comments, generated tests, and regression risks."
    ],
    []
  );

  const handleAnalyze = async (repoUrl: string) => {
    setIsPending(true);
    setError(null);
    setReport(null);

    try {
      const res = await fetch("/api/analysis/run", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ repoUrl })
      });

      if (!res.ok) {
        const errBody = await res.json();
        throw new Error(errBody.error || "Failed to run analysis");
      }

      const data: AnalysisReport | string = await res.json();
      if (!data || typeof data !== "object") {
        throw new Error("Unexpected response from analysis service");
      }

      setReport(data as AnalysisReport);
    } catch (e: any) {
      setError(e.message);
    } finally {
      setIsPending(false);
    }
  };

  return (
    <main>
      <Container size="3" py="8">
        <Flex direction="column" align="center" gap="2">
          <AuraLogo />
          <Heading as="h2" size="5" weight="light" color="gray">Autonomous Code Analysis</Heading>
        </Flex>

        <Card mt="4">
          <Flex direction="column" gap="2">
            {introText.map((line, idx) => (
              <Text key={idx} size="2" color="gray">{line}</Text>
            ))}
          </Flex>
        </Card>

        <RepoForm onSubmit={handleAnalyze} isPending={isPending} />

        {error && <Text color="red" mt="4">Error: {error}</Text>}

        {!error && isPending && (
          <Card mt="4">
            <Text size="2" color="gray">Running agents and collecting results...</Text>
          </Card>
        )}

        <RepoSummaryCard report={report} />

      </Container>
    </main>
  );
}
